{ pkgs, ... }: {
  # ── Hardware ──────────────────────────────────────────────────────────────────
  # Generated by nixos-generate-config during install; add to this directory.
  imports = [ ./hardware-configuration.nix ];

  # ── Bootloader ────────────────────────────────────────────────────────────────
  boot.loader = {
    efi.canTouchEfiVariables = true;
    grub = {
      enable = true;
      efiSupport = true;
      device = "nodev";
      useOSProber = true; # detects Windows for dual-boot menu entry
    };
  };

  # ── System identity ───────────────────────────────────────────────────────────
  networking.hostName = "mactan";
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings.LC_ALL = "en_US.UTF-8";

  # ── System user ───────────────────────────────────────────────────────────────
  users.users.philip = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "wheel" "networkmanager" ];
  };

  networking.networkmanager.enable = true;

  # ── Modules ───────────────────────────────────────────────────────────────────
  phix.nix.enable = true;

  # ── home-manager ──────────────────────────────────────────────────────────────
  home-manager.users.philip = {
    imports = [ ../../users/phil-personal.nix ];
    phix.desktop.enable = true;
  };

  # ── Extra ─────────────────────────────────────────────────────────────────────
  programs.hyprland.enable = true;
  programs.zsh.enable = true;
  nixpkgs.config.allowUnfree = true;
  home-manager.backupFileExtension = "bak";

  system.stateVersion = "24.11";
}
