{ pkgs, lib, ... }:
{
  # ── Hardware ──────────────────────────────────────────────────────────────────
  # Generated by nixos-generate-config during install; add to this directory.
  imports = [ ./hardware-configuration.nix ];

  hardware.graphics.enable = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings.General.Experimental = true;
  };

  # ── Bootloader ────────────────────────────────────────────────────────────────
  boot.loader = {
    efi.canTouchEfiVariables = true;
    grub = {
      enable = true;
      efiSupport = true;
      device = "nodev";
      useOSProber = true; # detects Windows for dual-boot menu entry
    };
  };

  # ── System identity ───────────────────────────────────────────────────────────
  networking.hostName = "mactan";
  networking.networkmanager.enable = true;
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings.LC_ALL = "en_US.UTF-8";

  # ── System user ───────────────────────────────────────────────────────────────
  users.users.philip = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "networkmanager"
    ];
  };

  # ── Modules ───────────────────────────────────────────────────────────────────
  phix.nix.enable = true;

  # ── Services ──────────────────────────────────────────────────────────────────
  services = {
    asusd.enable = true;
    blueman.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };
  };

  # ── Console ───────────────────────────────────────────────────────────────────
  console = {
    font = "ter-v32n";
    packages = [ pkgs.terminus_font ];
  };

  # ── home-manager ──────────────────────────────────────────────────────────────
  home-manager.users.philip = {
    imports = [ ../../users/phil-personal.nix ];
    phix.desktop = {
      enable = true;
      launcher = "rofi";
      wallpaper = "~/wallpapers/wall1.jpg";
    };
    
    programs.firefox = {
      enable = true;
      profiles.default = {
        isDefault = true;
        extensions.force = true;
      };
    };
    wayland.windowManager.hyprland.settings = {
      env = [
        # TODO: verify these are actually needed for AMD Phoenix
        # WLR_NO_HARDWARE_CURSORS fixes cursor rendering bugs on some AMD Wayland setups
        # AQ_DRM_DEVICES forces Hyprland to use card1 — may not be necessary
        "WLR_NO_HARDWARE_CURSORS,1"
        "AQ_DRM_DEVICES,/dev/dri/card1"
      ];
      # TODO: verify this is actually needed — disabled due to suspected AMD rendering issues
      decoration.blur.enabled = false;
      monitor = [
        "HDMI-A-1,3440x1440@84.96,0x0,1"
        "eDP-1,1920x1200@120,3440x0,1"
      ];
      workspace = [
        "1, monitor:HDMI-A-1, default:true"
        "2, monitor:HDMI-A-1"
        "3, monitor:HDMI-A-1"
        "4, monitor:HDMI-A-1"
        "5, monitor:eDP-1, default:true"
      ];
    };
  };

  # ── SSH ───────────────────────────────────────────────────────────────────
  programs.ssh.knownHosts = {
    "github.com-ed25519" = {
      hostNames = [ "github.com" ];
      publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl";
    };
    "github.com-ecdsa" = {
      hostNames = [ "github.com" ];
      publicKey = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=";
    };
    "github.com-rsa" = {
      hostNames = [ "github.com" ];
      publicKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=";
    };
  };

  # ── Extra ─────────────────────────────────────────────────────────────────────
  programs.hyprland.enable = true;

  system.stateVersion = "24.11";
}
